# site settings
title: Icaro's Notes
subtitle: 
email: icarosadero@gmail.com
description: A blog about math, physics, programming and areas alike.
baseurl: "/notes" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Ícaro Costa
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/icarosadero
  # GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  # Instagram:
  LinkedIn: https://www.linkedin.com/in/icarolorran/
  # Twitter: https://twitter.com/andrewbanchich
  # Facebook:
  # Slack:

# build settings
markdown: kramdown

plugins:
  - jekyll-mermaid
  - jekyll-feed
  - jekyll/scholar

mermaid:
  src: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  options: { "theme": "dark" }

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 